"""
PDF Export functionality for meal plans with Fitomics branding
"""
from fpdf import FPDF
import os
from datetime import datetime
import json
import traceback
import unicodedata
import re

def clean_text_for_pdf(text):
    """Clean text to ensure it's compatible with PDF latin-1 encoding"""
    if not text:
        return ""
    
    # Convert to string if not already
    text = str(text)
    
    # Normalize unicode characters
    text = unicodedata.normalize('NFKD', text)
    
    # Remove or replace problematic characters
    text = text.replace('•', '-')  # Replace bullet points with dashes
    text = text.replace('–', '-')  # Replace em dash with hyphen
    text = text.replace('—', '-')  # Replace en dash with hyphen
    text = text.replace('"', '"')  # Replace curly quotes
    text = text.replace('"', '"')
    text = text.replace(''', "'")  # Replace curly apostrophes
    text = text.replace(''', "'")
    text = text.replace('…', '...')  # Replace ellipsis
    text = text.replace('°', ' degrees')  # Replace degree symbol
    text = text.replace('½', '1/2')  # Replace fraction
    text = text.replace('¼', '1/4')
    text = text.replace('¾', '3/4')
    text = text.replace('™', '')  # Remove trademark symbol
    text = text.replace('®', '')  # Remove registered symbol
    text = text.replace('©', '')  # Remove copyright symbol
    text = re.sub(r'[^\x20-\x7E]', '', text)  # Keep only printable ASCII characters
    
    # Ensure it's encodable in latin-1
    try:
        text.encode('latin-1')
    except UnicodeEncodeError:
        # If still problematic, keep only ASCII characters
        text = ''.join(char for char in text if ord(char) < 128)
    
    return text

class FitomicsPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        
    def header(self):
        """Add Fitomics branded header"""
        # Try multiple logo paths
        logo_paths = [
            "attached_assets/fitomicshorizontalgold.png",
            "attached_assets/Fitomics Logomark – Dark Blue.png",
            "attached_assets/Fitomics Logomark – Dark Gold.png"
        ]
        
        logo_added = False
        for logo_path in logo_paths:
            if os.path.exists(logo_path):
                try:
                    self.image(logo_path, 10, 8, 40)
                    logo_added = True
                    break
                except:
                    continue
        
        # Fitomics branding text
        if not logo_added:
            self.set_font('Arial', 'B', 24)
            self.set_text_color(193, 153, 98)  # Fitomics gold
            self.cell(0, 15, 'FITOMICS', 0, 1, 'C')
        else:
            self.ln(20)
        
        self.set_font('Arial', '', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'Personalized Nutrition & Body Composition Planning', 0, 1, 'C')
        self.ln(10)
        
    def footer(self):
        """Add footer with page number and branding"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by Fitomics AI - Page {self.page_no()}', 0, 0, 'C')
        
    def add_title_page(self, user_info, plan_info):
        """Add a branded title page"""
        self.add_page()
        
        # Main title
        self.ln(20)
        self.set_font('Arial', 'B', 28)
        self.set_text_color(41, 84, 144)
        self.cell(0, 15, 'AI MEAL PLAN', 0, 1, 'C')
        
        self.set_font('Arial', '', 16)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'Personalized Nutrition Strategy', 0, 1, 'C')
        
        # User info section
        self.ln(20)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, 'PLAN DETAILS', 0, 1, 'L')
        
        self.set_font('Arial', '', 12)
        self.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y')}", 0, 1, 'L')
        
        # Add profile summary if available
        if user_info and 'profile' in user_info:
            profile = user_info['profile']
            goals = user_info.get('goals', {})
            
            if profile:
                self.ln(5)
                self.set_font('Arial', 'B', 14)
                self.cell(0, 8, 'PROFILE SUMMARY', 0, 1, 'L')
                
                self.set_font('Arial', '', 12)
                if profile.get('name'):
                    self.cell(0, 6, f"Name: {profile['name']}", 0, 1, 'L')
                if profile.get('age'):
                    self.cell(0, 6, f"Age: {profile['age']} years", 0, 1, 'L')
                if profile.get('gender'):
                    self.cell(0, 6, f"Gender: {profile['gender']}", 0, 1, 'L')
                if profile.get('weight_lbs'):
                    self.cell(0, 6, f"Weight: {profile['weight_lbs']} lbs", 0, 1, 'L')
                if profile.get('height_ft') and profile.get('height_in'):
                    self.cell(0, 6, f"Height: {profile['height_ft']}'{profile['height_in']}\"", 0, 1, 'L')
                if profile.get('activity_level'):
                    self.cell(0, 6, f"Activity Level: {profile['activity_level']}", 0, 1, 'L')
                
                # Add goals if available
                if goals:
                    self.ln(3)
                    self.set_font('Arial', 'B', 12)
                    self.cell(0, 6, 'Goals:', 0, 1, 'L')
                    self.set_font('Arial', '', 12)
                    if goals.get('goal_type'):
                        self.cell(0, 6, f"Primary Goal: {goals['goal_type']}", 0, 1, 'L')
                    if goals.get('target_weight_lbs'):
                        self.cell(0, 6, f"Target Weight: {goals['target_weight_lbs']} lbs", 0, 1, 'L')
                    if goals.get('target_bf'):
                        self.cell(0, 6, f"Target Body Fat: {goals['target_bf']}%", 0, 1, 'L')
        # Show daily totals from meal plan data
        if user_info and user_info.get('daily_totals'):
            daily_totals = user_info['daily_totals']
            avg_calories = daily_totals.get('calories', 0)
            avg_protein = daily_totals.get('protein', 0)
            avg_carbs = daily_totals.get('carbs', 0)
            avg_fat = daily_totals.get('fat', 0)
        elif plan_info.get('daily_totals'):
            daily_totals = plan_info['daily_totals']
            avg_calories = daily_totals.get('calories', 0)
            avg_protein = daily_totals.get('protein', 0)
            avg_carbs = daily_totals.get('carbs', 0)
            avg_fat = daily_totals.get('fat', 0)
        else:
            # Calculate totals from actual meal data
            avg_calories = 0
            avg_protein = 0
            avg_carbs = 0
            avg_fat = 0
            
            # Get totals from meal plan data if available
            if hasattr(plan_info, 'get') and plan_info.get('meal_data'):
                meal_data = plan_info['meal_data']
                if isinstance(meal_data, list):
                    for meal in meal_data:
                        if 'recipe' in meal and 'macros' in meal['recipe']:
                            macros = meal['recipe']['macros']
                            avg_calories += macros.get('calories', 0)
                            avg_protein += macros.get('protein', 0)
                            avg_carbs += macros.get('carbs', 0)
                            avg_fat += macros.get('fat', 0)
            
            # Fallback to calculated averages if daily_totals not available
            if avg_calories == 0:
                avg_calories = plan_info.get('total_calories', 0) / 7 if plan_info.get('total_calories') else 0
                avg_protein = plan_info.get('total_protein', 0) / 7 if plan_info.get('total_protein') else 0
                avg_carbs = plan_info.get('total_carbs', 0) / 7 if plan_info.get('total_carbs') else 0
                avg_fat = plan_info.get('total_fat', 0) / 7 if plan_info.get('total_fat') else 0
        
        self.cell(0, 6, f"Average Daily Calories: {avg_calories:.0f}", 0, 1, 'L')
        self.cell(0, 6, f"Average Daily Protein: {avg_protein:.1f}g", 0, 1, 'L')
        self.cell(0, 6, f"Average Daily Carbohydrates: {avg_carbs:.1f}g", 0, 1, 'L')
        self.cell(0, 6, f"Average Daily Fat: {avg_fat:.1f}g", 0, 1, 'L')
        
        # Add accuracy comparison if target data is available
        if plan_info.get('daily_accuracy_comparison'):
            self.ln(10)
            self.set_font('Arial', 'B', 14)
            self.cell(0, 8, 'MACRO ACCURACY COMPARISON', 0, 1, 'L')
            
            self.set_font('Arial', '', 10)
            self.cell(0, 5, 'Daily Target vs Actual Results:', 0, 1, 'L')
            self.ln(3)
            
            # Create table header
            self.set_font('Arial', 'B', 9)
            self.cell(25, 6, 'Day', 1, 0, 'C')
            self.cell(30, 6, 'Calories', 1, 0, 'C')
            self.cell(30, 6, 'Protein', 1, 0, 'C')
            self.cell(30, 6, 'Carbs', 1, 0, 'C')
            self.cell(30, 6, 'Fat', 1, 0, 'C')
            self.cell(25, 6, 'Accuracy', 1, 1, 'C')
            
            # Add data rows
            self.set_font('Arial', '', 8)
            for day_data in plan_info['daily_accuracy_comparison']:
                self.cell(25, 5, day_data['day'][:3], 1, 0, 'C')
                self.cell(30, 5, f"{day_data['actual_cal']:.0f}/{day_data['target_cal']:.0f}", 1, 0, 'C')
                self.cell(30, 5, f"{day_data['actual_protein']:.0f}/{day_data['target_protein']:.0f}", 1, 0, 'C')
                self.cell(30, 5, f"{day_data['actual_carbs']:.0f}/{day_data['target_carbs']:.0f}", 1, 0, 'C')
                self.cell(30, 5, f"{day_data['actual_fat']:.0f}/{day_data['target_fat']:.0f}", 1, 0, 'C')
                self.cell(25, 5, day_data['accuracy_score'], 1, 1, 'C')
            
            self.ln(3)
            self.set_font('Arial', 'I', 8)
            self.cell(0, 4, clean_text_for_pdf('Format: Actual/Target | Check = Within 5% | Warning = Outside 5%'), 0, 1, 'L')
        
        # Diet preferences
        diet_prefs = plan_info.get('diet_preferences', {})
        if any(diet_prefs.values()):
            self.ln(10)
            self.set_font('Arial', 'B', 14)
            self.cell(0, 8, 'DIETARY PREFERENCES', 0, 1, 'L')
            
            self.set_font('Arial', '', 12)
            prefs = []
            if diet_prefs.get('vegetarian'): prefs.append('Vegetarian')
            if diet_prefs.get('vegan'): prefs.append('Vegan')
            if diet_prefs.get('gluten_free'): prefs.append('Gluten-Free')
            if diet_prefs.get('dairy_free'): prefs.append('Dairy-Free')
            
            for pref in prefs:
                self.cell(0, 6, f"- {pref}", 0, 1, 'L')
                
    def add_meal_section(self, meal_type, recipe, macros, ingredients, meal_context=None, meal_time=None, workout_annotation=None, day_name=None):
        """Add a meal section with recipe and ingredients"""
        # Meal title with day context
        self.set_font('Arial', 'B', 16)
        self.set_text_color(41, 84, 144)
        if day_name:
            title = f"{day_name.upper()} - {clean_text_for_pdf(meal_type).upper()}"
        else:
            title = clean_text_for_pdf(meal_type).upper()
        self.cell(0, 10, title, 0, 1, 'L')
        
        # Recipe name (only if different from meal type)
        recipe_name = recipe.get('name', recipe.get('title', ''))
        if recipe_name and recipe_name.lower() != meal_type.lower():
            self.set_font('Arial', 'B', 12)
            self.set_text_color(0, 0, 0)
            self.cell(0, 6, clean_text_for_pdf(recipe_name), 0, 1, 'L')
        
        # Add meal context and time if available
        if meal_context or meal_time:
            self.set_font('Arial', '', 10)
            self.set_text_color(100, 100, 100)
            context_parts = []
            if meal_time:
                context_parts.append(f"Time: {clean_text_for_pdf(meal_time)}")
            if meal_context:
                context_parts.append(f"Context: {clean_text_for_pdf(meal_context)}")
            self.cell(0, 5, " | ".join(context_parts), 0, 1, 'L')
            self.set_text_color(0, 0, 0)
        
        # Add workout annotation if available
        if workout_annotation:
            self.set_font('Arial', 'B', 10)
            self.set_text_color(255, 140, 0)  # Orange color for workout annotations
            self.cell(0, 5, f"Workout: {clean_text_for_pdf(workout_annotation)}", 0, 1, 'L')
            self.set_text_color(0, 0, 0)
        
        # Macros box
        self.ln(2)
        self.set_fill_color(245, 245, 245)
        self.rect(10, self.get_y(), 190, 20, 'F')
        
        # Macros in columns
        y_pos = self.get_y() + 5
        self.set_xy(15, y_pos)
        self.set_font('Arial', 'B', 10)
        
        # Format macro values properly
        calories = int(macros.get('calories', 0)) if macros.get('calories') else 0
        protein = round(float(macros.get('protein', 0)), 1) if macros.get('protein') else 0
        carbs = round(float(macros.get('carbs', 0)), 1) if macros.get('carbs') else 0
        fat = round(float(macros.get('fat', 0)), 1) if macros.get('fat') else 0
        
        self.cell(45, 5, f"Calories: {calories}", 0, 0, 'L')
        self.set_x(60)
        self.cell(45, 5, f"Protein: {protein}g", 0, 0, 'L')
        self.set_x(105)
        self.cell(45, 5, f"Carbs: {carbs}g", 0, 0, 'L')
        self.set_x(150)
        self.cell(45, 5, f"Fat: {fat}g", 0, 1, 'L')
        
        self.ln(15)
        
        # Ingredients
        self.set_font('Arial', 'B', 12)
        self.cell(0, 6, 'INGREDIENTS:', 0, 1, 'L')
        
        self.set_font('Arial', '', 10)
        for ingredient in ingredients:
            if isinstance(ingredient, dict):
                # Try different keys for ingredient name
                name = ingredient.get('item', ingredient.get('name', 'Unknown'))
                amount = ingredient.get('amount', 0)
                # Clean up amount formatting - preserve units
                if isinstance(amount, str):
                    self.cell(0, 5, f"- {clean_text_for_pdf(amount)} {clean_text_for_pdf(name)}", 0, 1, 'L')
                else:
                    self.cell(0, 5, f"- {amount}g {clean_text_for_pdf(name)}", 0, 1, 'L')
            else:
                self.cell(0, 5, f"- {clean_text_for_pdf(ingredient)}", 0, 1, 'L')
        
        # Instructions/Directions
        instructions = recipe.get('instructions', recipe.get('directions', []))
        if instructions:
            self.ln(3)
            self.set_font('Arial', 'B', 12)
            self.cell(0, 6, 'INSTRUCTIONS:', 0, 1, 'L')
            
            self.set_font('Arial', '', 10)
            if isinstance(instructions, list):
                for i, instruction in enumerate(instructions, 1):
                    instruction_text = clean_text_for_pdf(instruction)
                    # Handle long instructions by wrapping text
                    if len(instruction_text) > 100:
                        # Split into multiple lines
                        words = instruction_text.split()
                        current_line = f"{i}. "
                        for word in words:
                            if len(current_line + word) > 95:
                                self.cell(0, 4, current_line, 0, 1, 'L')
                                current_line = "   " + word + " "
                            else:
                                current_line += word + " "
                        if current_line.strip():
                            self.cell(0, 4, current_line, 0, 1, 'L')
                    else:
                        self.cell(0, 4, f"{i}. {instruction_text}", 0, 1, 'L')
            else:
                # Split text instructions into lines
                lines = str(instructions).split('. ')
                for i, line in enumerate(lines, 1):
                    if line.strip():
                        line_text = clean_text_for_pdf(line.strip())
                        if len(line_text) > 100:
                            words = line_text.split()
                            current_line = f"{i}. "
                            for word in words:
                                if len(current_line + word) > 95:
                                    self.cell(0, 4, current_line, 0, 1, 'L')
                                    current_line = "   " + word + " "
                                else:
                                    current_line += word + " "
                            if current_line.strip():
                                self.cell(0, 4, current_line, 0, 1, 'L')
                        else:
                            self.cell(0, 4, f"{i}. {line_text}", 0, 1, 'L')
        
        self.ln(8)
        
    def add_grocery_list(self, all_ingredients):
        """Add consolidated grocery list with proper totaling"""
        self.add_page()
        
        self.set_font('Arial', 'B', 18)
        self.set_text_color(41, 84, 144)
        self.cell(0, 12, 'CONSOLIDATED GROCERY LIST', 0, 1, 'L')
        self.ln(5)
        
        # Properly consolidate ingredients by name and sum amounts
        consolidated = {}
        
        for ingredient in all_ingredients:
            if isinstance(ingredient, dict):
                name = ingredient.get('name', ingredient.get('item', ''))
                amount_str = str(ingredient.get('amount', ''))
                
                # Skip empty names or amounts
                if not name or not amount_str:
                    continue
                
                # Clean and normalize the name
                clean_name = name.strip().title()
                
                # Parse amount and unit
                amount_parts = amount_str.strip().split()
                if len(amount_parts) >= 1:
                    # Try to extract numeric amount
                    try:
                        # Extract numeric value
                        amount_clean = amount_parts[0].replace('g', '').replace('ml', '').replace('tbsp', '').replace('large', '')
                        numeric_amount = float(amount_clean)
                        
                        # Extract unit properly
                        if 'g' in amount_str:
                            unit = 'g'
                        elif 'ml' in amount_str:
                            unit = 'ml'
                        elif 'tbsp' in amount_str:
                            unit = ' tbsp'
                        elif 'large' in amount_str:
                            unit = ' large'
                        else:
                            unit = ' ' + ' '.join(amount_parts[1:]) if len(amount_parts) > 1 else ''
                            
                        # Store in consolidated with proper totaling
                        if clean_name in consolidated:
                            # Add to existing total
                            existing_amount, existing_unit = consolidated[clean_name]
                            if existing_unit == unit:
                                consolidated[clean_name] = (existing_amount + numeric_amount, unit)
                            else:
                                # Different units - keep separate for now
                                consolidated[f"{clean_name} ({unit})"] = (numeric_amount, unit)
                        else:
                            consolidated[clean_name] = (numeric_amount, unit)
                    except ValueError:
                        # Non-numeric amount - store as string
                        if clean_name in consolidated:
                            if isinstance(consolidated[clean_name], list):
                                consolidated[clean_name].append(amount_str)
                            else:
                                consolidated[clean_name] = [consolidated[clean_name], amount_str]
                        else:
                            consolidated[clean_name] = amount_str
        
        # Sort and display with proper totals
        self.set_font('Arial', '', 11)
        self.set_text_color(0, 0, 0)
        
        for name, amounts in sorted(consolidated.items()):
            if name:
                if isinstance(amounts, tuple):
                    # Numeric total
                    total_amount, unit = amounts
                    if total_amount == int(total_amount):
                        total_amount = int(total_amount)
                    total_str = f"{total_amount}{unit}" if unit else str(total_amount)
                    self.cell(0, 6, f"- {clean_text_for_pdf(name)}: {total_str}", 0, 1, 'L')
                elif isinstance(amounts, list):
                    # Multiple non-numeric amounts
                    self.cell(0, 6, f"- {clean_text_for_pdf(name)}:", 0, 1, 'L')
                    self.set_font('Arial', '', 10)
                    for amount in amounts:
                        self.cell(0, 4, f"  • {clean_text_for_pdf(amount)}", 0, 1, 'L')
                    self.set_font('Arial', '', 11)
                else:
                    # Single amount
                    self.cell(0, 6, f"- {clean_text_for_pdf(name)}: {clean_text_for_pdf(amounts)}", 0, 1, 'L')
    
    def add_organized_grocery_list(self, all_ingredients):
        """Add organized grocery list by category"""
        self.add_page()
        
        self.set_font('Arial', 'B', 18)
        self.set_text_color(41, 84, 144)
        self.cell(0, 12, 'ORGANIZED GROCERY LIST', 0, 1, 'L')
        
        # Organize ingredients by category
        categories = {
            'protein': [],
            'carbs': [],
            'fats': [],
            'vegetables': [],
            'seasonings': [],
            'other': []
        }
        
        for ingredient in all_ingredients:
            if isinstance(ingredient, dict):
                category = ingredient.get('category', 'other')
                name = ingredient.get('name', ingredient.get('item', ''))
                amount = ingredient.get('amount', ingredient.get('total_amount', ''))
                
                if name and amount:
                    categories[category].append(f"{name}: {amount}")
        
        # Display by category
        category_names = {
            'protein': 'PROTEINS',
            'carbs': 'CARBOHYDRATES',
            'fats': 'FATS & OILS',
            'vegetables': 'VEGETABLES & FRUITS',
            'seasonings': 'SEASONINGS & SPICES',
            'other': 'OTHER ITEMS'
        }
        
        for category, items in categories.items():
            if items:
                self.ln(3)
                self.set_font('Arial', 'B', 14)
                self.set_text_color(41, 84, 144)
                self.cell(0, 8, category_names[category], 0, 1, 'L')
                
                self.set_font('Arial', '', 11)
                self.set_text_color(0, 0, 0)
                for item in sorted(items):
                    self.cell(0, 5, f"- {clean_text_for_pdf(item)}", 0, 1, 'L')

def export_meal_plan_pdf(meal_data, user_preferences=None, plan_info=None):
    """Export complete meal plan with grocery list to branded PDF"""
    try:
        print("Starting PDF creation...")
        print(f"Meal data type: {type(meal_data)}")
        print(f"Meal data length: {len(meal_data) if meal_data else 'None'}")
        
        # Validate meal data exists
        if not meal_data:
            raise ValueError("No meal data provided for PDF export")
        
        # Debug: Print first few items to understand structure
        if meal_data:
            print("First meal data sample:")
            if isinstance(meal_data, list) and len(meal_data) > 0:
                print(json.dumps(meal_data[0], indent=2, default=str))
            elif isinstance(meal_data, dict):
                first_key = list(meal_data.keys())[0] if meal_data else None
                if first_key:
                    print(f"First key: {first_key}")
                    print(json.dumps(meal_data[first_key], indent=2, default=str))
        
        pdf = FitomicsPDF()
        
        # Safely extract plan info with error handling
        total_calories = 0
        total_protein = 0
        total_carbs = 0
        total_fat = 0
        
        print(f"Processing {len(meal_data)} meals...")
        
        # Handle both dictionary and list formats
        if isinstance(meal_data, dict):
            meals_to_process = meal_data.values()
        else:
            meals_to_process = meal_data
            
        for meal in meals_to_process:
            # Handle different meal data structures
            if isinstance(meal, dict):
                # Check for recipe structure first
                if 'recipe' in meal and isinstance(meal['recipe'], dict):
                    recipe_macros = meal['recipe'].get('macros', {})
                    total_calories += float(recipe_macros.get('calories', 0) or 0)
                    total_protein += float(recipe_macros.get('protein', 0) or 0)
                    total_carbs += float(recipe_macros.get('carbs', 0) or 0)
                    total_fat += float(recipe_macros.get('fat', 0) or 0)
                    continue
                
                # Try different possible macro locations
                macros = meal.get('macros', meal.get('total_macros', {}))
                if not macros and 'calories' in meal:
                    macros = meal  # The meal itself contains the macros
                    
                # Handle meals array from AI response
                if 'meals' in meal:
                    for submeal in meal['meals']:
                        submacros = submeal.get('total_macros', {})
                        total_calories += float(submacros.get('calories', 0) or 0)
                        total_protein += float(submacros.get('protein', 0) or 0)
                        total_carbs += float(submacros.get('carbs', 0) or 0)
                        total_fat += float(submacros.get('fat', 0) or 0)
                else:
                    total_calories += float(macros.get('calories', 0) or 0)
                    total_protein += float(macros.get('protein', 0) or 0)
                    total_carbs += float(macros.get('carbs', 0) or 0)
                    total_fat += float(macros.get('fat', 0) or 0)
        
        # Use passed plan_info or create default
        if not plan_info:
            plan_info = {
                'total_calories': int(total_calories),
                'total_protein': round(total_protein, 1),
                'total_carbs': round(total_carbs, 1),
                'total_fat': round(total_fat, 1),
                'diet_preferences': user_preferences or {}
            }
        
        # Add meal data to plan_info for macro calculation
        if 'meal_data' not in plan_info:
            plan_info['meal_data'] = meal_data
        
        print("Adding title page...")
        # Add title page
        pdf.add_title_page(user_preferences or {}, plan_info)
        
        print("Adding meals page...")
        # Add meals page
        pdf.add_page()
        pdf.set_font('Arial', 'B', 20)
        pdf.set_text_color(193, 153, 98)  # Fitomics gold
        pdf.cell(0, 12, 'DAILY MEAL PLAN', 0, 1, 'L')
        pdf.ln(5)
        
        all_ingredients = []
        
        # Check if this is weekly meal data (has day names as keys)
        if isinstance(meal_data, dict) and any(day in meal_data for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']):
            # Organize meals by day for better PDF structure
            days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
            
            for day in days_order:
                if day not in meal_data:
                    continue
                    
                day_data = meal_data[day]
                print(f"Processing {day}")
                
                # Add day header
                pdf.ln(10)
                pdf.set_font('Arial', 'B', 20)
                pdf.set_text_color(41, 84, 144)
                pdf.cell(0, 12, f"{day.upper()}", 0, 1, 'L')
                pdf.ln(5)
                
                # Process meals for this day
                meals = day_data.get('meals', [])
                for i, meal_info in enumerate(meals):
                    if not meal_info:
                        continue
                        
                    # Use simple meal naming
                    if i < 3:
                        meal_type = f"Meal {i+1}"
                    else:
                        meal_type = f"Snack {i-2}"
                    
                    print(f"  Processing {meal_type}")
                    
                    # Extract meal components
                    meal_name = meal_info.get('name', meal_type)
                    meal_time = meal_info.get('time', '')
                    meal_context = meal_info.get('context', '')
                    ingredients = meal_info.get('ingredients', [])
                    instructions = meal_info.get('instructions', [])
                    total_macros = meal_info.get('total_macros', {})
                    
                    # Create recipe structure for PDF
                    recipe = {
                        'name': meal_name,
                        'ingredients': ingredients,
                        'instructions': instructions
                    }
                    
                    # Add to PDF with day context
                    pdf.add_meal_section(
                        meal_type=meal_type,
                        recipe=recipe,
                        macros=total_macros,
                        ingredients=ingredients,
                        meal_context=meal_context,
                        meal_time=meal_time,
                        day_name=day
                    )
                    
                    # Collect ingredients for grocery list
                    for ingredient in ingredients:
                        if isinstance(ingredient, dict):
                            all_ingredients.append({
                                'name': ingredient.get('item', ''),
                                'amount': ingredient.get('amount', ''),
                                'unit': 'serving'
                            })
        else:
            # Handle legacy single-day or non-daily format
            if isinstance(meal_data, dict):
                items_to_process = meal_data.items()
            else:
                items_to_process = enumerate(meal_data)
                
            for meal_identifier, meal_info in items_to_process:
                if isinstance(meal_identifier, int):
                    meal_type = meal_info.get('meal_type', meal_info.get('name', f'Meal {meal_identifier + 1}'))
                else:
                    meal_type = meal_identifier
                    
                print(f"Processing meal: {meal_type}")
                
                # Handle recipe structure from AI meal planning
                if 'recipe' in meal_info:
                    recipe = meal_info['recipe']
                    meal_name = recipe.get('name', meal_type)
                    macros = recipe.get('macros', {})
                    ingredients = recipe.get('ingredients', [])
                    
                    # Add to PDF with context
                    pdf.add_meal_section(
                        meal_type=meal_name,
                        recipe=recipe,
                        macros=macros,
                        ingredients=ingredients,
                        meal_context=meal_info.get('context'),
                        meal_time=meal_info.get('time')
                    )
                    
                    # Collect ingredients for grocery list
                    for ingredient in ingredients:
                        if isinstance(ingredient, dict):
                            all_ingredients.append({
                                'name': ingredient.get('item', ingredient.get('name', '')),
                                'amount': ingredient.get('amount', ''),
                                'unit': 'serving'
                            })
                    continue
                
                # Single meal structure (fallback)
                recipe = meal_info.get('recipe', meal_info)
                macros = meal_info.get('macros', meal_info.get('total_macros', {}))
                ingredients = meal_info.get('ingredient_details', meal_info.get('ingredients', []))
            
            if ingredients:
                all_ingredients.extend(ingredients)
            
            pdf.add_meal_section(
                meal_type=meal_type,
                recipe=recipe,
                macros=macros,
                ingredients=ingredients,
                meal_context=meal_info.get('context'),
                meal_time=meal_info.get('time')
            )
        
        print(f"Adding grocery list with {len(all_ingredients)} ingredients...")
        # Add grocery list on new page
        if all_ingredients:
            pdf.add_grocery_list(all_ingredients)
        
        # Return PDF as bytes buffer for download
        print("Creating PDF buffer...")
        pdf_string = pdf.output(dest='S')
        pdf_output = pdf_string.encode('latin1') if isinstance(pdf_string, str) else pdf_string
        print("PDF created successfully!")
        return pdf_output
        
    except Exception as e:
        print(f"Error creating PDF: {e}")
        print(f"Full traceback: {traceback.format_exc()}")
        return None

def export_enhanced_weekly_meal_plan_pdf(weekly_meal_data, user_preferences=None):
    """Export enhanced weekly meal plan with profile summaries, workout annotations, and organized grocery lists"""
    try:
        print("Starting enhanced weekly PDF creation...")
        
        if not weekly_meal_data:
            raise ValueError("No weekly meal data provided for PDF export")
        
        pdf = FitomicsPDF()
        
        # Calculate weekly totals
        weekly_totals = {'calories': 0, 'protein': 0, 'carbs': 0, 'fat': 0}
        all_ingredients = []
        
        # Extract profile summaries and workout info
        profile_summaries = []
        workout_info = []
        
        for day, day_data in weekly_meal_data.items():
            if isinstance(day_data, dict):
                # Add profile summary if available
                if 'profile_summary' in day_data:
                    profile_summaries.append(f"{day}: {day_data['profile_summary']}")
                
                # Add workout info if available
                if 'workout_annotations' in day_data:
                    workout_data = day_data['workout_annotations']
                    if workout_data.get('has_workout'):
                        workout_info.append(f"{day}: {workout_data.get('workout_details', 'Workout scheduled')}")
                
                # Add to weekly totals
                daily_totals = day_data.get('daily_totals', {})
                for macro in weekly_totals:
                    weekly_totals[macro] += daily_totals.get(macro, 0)
                
                # Collect organized ingredients
                if 'grocery_ingredients' in day_data:
                    for ingredient in day_data['grocery_ingredients']:
                        all_ingredients.append({
                            'name': ingredient.get('item', ''),
                            'amount': ingredient.get('total_amount', ''),
                            'category': ingredient.get('category', 'other'),
                            'day': day
                        })
        
        # Create enhanced plan info
        plan_info = {
            'total_calories': int(weekly_totals['calories'] / 7),  # Daily average
            'total_protein': round(weekly_totals['protein'] / 7, 1),
            'total_carbs': round(weekly_totals['carbs'] / 7, 1),
            'total_fat': round(weekly_totals['fat'] / 7, 1),
            'diet_preferences': user_preferences or {},
            'profile_summaries': profile_summaries,
            'workout_info': workout_info
        }
        
        # Add enhanced title page
        pdf.add_title_page({}, plan_info)
        
        # Add profile summary page
        if profile_summaries:
            pdf.add_page()
            pdf.set_font('Arial', 'B', 18)
            pdf.set_text_color(41, 84, 144)
            pdf.cell(0, 12, 'HOW YOUR PREFERENCES SHAPED YOUR PLAN', 0, 1, 'L')
            pdf.ln(5)
            
            pdf.set_font('Arial', '', 11)
            pdf.set_text_color(0, 0, 0)
            for summary in profile_summaries:
                pdf.cell(0, 6, summary, 0, 1, 'L')
                pdf.ln(2)
        
        # Add workout optimization page
        if workout_info:
            pdf.add_page()
            pdf.set_font('Arial', 'B', 18)
            pdf.set_text_color(41, 84, 144)
            pdf.cell(0, 12, 'WORKOUT OPTIMIZATION NOTES', 0, 1, 'L')
            pdf.ln(5)
            
            pdf.set_font('Arial', '', 11)
            pdf.set_text_color(0, 0, 0)
            for workout in workout_info:
                pdf.cell(0, 6, workout, 0, 1, 'L')
                pdf.ln(2)
        
        # Add daily meal plans
        for day, day_data in weekly_meal_data.items():
            if not isinstance(day_data, dict) or 'meals' not in day_data:
                continue
                
            pdf.add_page()
            pdf.set_font('Arial', 'B', 20)
            pdf.set_text_color(193, 153, 98)
            pdf.cell(0, 12, f'{day.upper()} MEAL PLAN', 0, 1, 'L')
            pdf.ln(5)
            
            # Add daily totals summary
            daily_totals = day_data.get('daily_totals', {})
            daily_targets = day_data.get('daily_targets', {})
            
            pdf.set_font('Arial', 'B', 12)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 6, 'DAILY SUMMARY:', 0, 1, 'L')
            
            pdf.set_font('Arial', '', 10)
            if daily_totals and daily_targets:
                pdf.cell(0, 5, f"Target: {daily_targets.get('calories', 0):.0f} cal | {daily_targets.get('protein', 0):.0f}g protein | {daily_targets.get('carbs', 0):.0f}g carbs | {daily_targets.get('fat', 0):.0f}g fat", 0, 1, 'L')
                pdf.cell(0, 5, f"Actual: {daily_totals.get('calories', 0):.0f} cal | {daily_totals.get('protein', 0):.0f}g protein | {daily_totals.get('carbs', 0):.0f}g carbs | {daily_totals.get('fat', 0):.0f}g fat", 0, 1, 'L')
                
                # Add accuracy summary
                accuracy = day_data.get('accuracy_summary', {})
                if accuracy:
                    pdf.set_font('Arial', 'B', 10)
                    pdf.set_text_color(0, 150, 0)
                    accuracy_text = f"Accuracy: {accuracy.get('calories', 'N/A')} cal | {accuracy.get('protein', 'N/A')} protein | {accuracy.get('carbs', 'N/A')} carbs | {accuracy.get('fat', 'N/A')} fat"
                    pdf.cell(0, 5, accuracy_text, 0, 1, 'L')
                    pdf.set_text_color(0, 0, 0)
            
            pdf.ln(5)
            
            # Add meals
            for meal in day_data['meals']:
                meal_name = clean_text_for_pdf(meal.get('name', 'Meal'))
                meal_macros = meal.get('total_macros', {})
                meal_ingredients = meal.get('ingredients', [])
                meal_context = clean_text_for_pdf(meal.get('context', ''))
                meal_time = clean_text_for_pdf(meal.get('time', ''))
                workout_annotation = clean_text_for_pdf(meal.get('workout_annotation', ''))
                
                pdf.add_meal_section(
                    meal_type=meal_name,
                    recipe=meal,
                    macros=meal_macros,
                    ingredients=meal_ingredients,
                    meal_context=meal_context,
                    meal_time=meal_time,
                    workout_annotation=workout_annotation
                )
        
        # Add organized grocery list
        if all_ingredients:
            pdf.add_organized_grocery_list(all_ingredients)
        
        # Save PDF
        filename = f"fitomics_weekly_meal_plan_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
        pdf.output(filename)
        print("Enhanced weekly PDF created successfully!")
        return filename
        
    except Exception as e:
        print(f"Error creating enhanced weekly PDF: {e}")
        print(f"Full traceback: {traceback.format_exc()}")
        return None