"""
PDF Export functionality for meal plans with Fitomics branding
"""
from fpdf import FPDF
import os
from datetime import datetime
import json
import traceback

class FitomicsPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        
    def header(self):
        """Add Fitomics branded header"""
        # Try multiple logo paths
        logo_paths = [
            "attached_assets/fitomicshorizontalgold.png",
            "attached_assets/Fitomics Logomark – Dark Blue.png",
            "attached_assets/Fitomics Logomark – Dark Gold.png"
        ]
        
        logo_added = False
        for logo_path in logo_paths:
            if os.path.exists(logo_path):
                try:
                    self.image(logo_path, 10, 8, 40)
                    logo_added = True
                    break
                except:
                    continue
        
        # Fitomics branding text
        if not logo_added:
            self.set_font('Arial', 'B', 24)
            self.set_text_color(193, 153, 98)  # Fitomics gold
            self.cell(0, 15, 'FITOMICS', 0, 1, 'C')
        else:
            self.ln(20)
        
        self.set_font('Arial', '', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, 'Personalized Nutrition & Body Composition Planning', 0, 1, 'C')
        self.ln(10)
        
    def footer(self):
        """Add footer with page number and branding"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by Fitomics AI - Page {self.page_no()}', 0, 0, 'C')
        
    def add_title_page(self, user_info, plan_info):
        """Add a branded title page"""
        self.add_page()
        
        # Main title
        self.ln(20)
        self.set_font('Arial', 'B', 28)
        self.set_text_color(41, 84, 144)
        self.cell(0, 15, 'AI MEAL PLAN', 0, 1, 'C')
        
        self.set_font('Arial', '', 16)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'Personalized Nutrition Strategy', 0, 1, 'C')
        
        # User info section
        self.ln(20)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, 'PLAN DETAILS', 0, 1, 'L')
        
        self.set_font('Arial', '', 12)
        self.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y')}", 0, 1, 'L')
        self.cell(0, 6, f"Daily Calories: {plan_info.get('total_calories', 'N/A')}", 0, 1, 'L')
        self.cell(0, 6, f"Protein: {plan_info.get('total_protein', 'N/A')}g", 0, 1, 'L')
        self.cell(0, 6, f"Carbohydrates: {plan_info.get('total_carbs', 'N/A')}g", 0, 1, 'L')
        self.cell(0, 6, f"Fat: {plan_info.get('total_fat', 'N/A')}g", 0, 1, 'L')
        
        # Diet preferences
        diet_prefs = plan_info.get('diet_preferences', {})
        if any(diet_prefs.values()):
            self.ln(10)
            self.set_font('Arial', 'B', 14)
            self.cell(0, 8, 'DIETARY PREFERENCES', 0, 1, 'L')
            
            self.set_font('Arial', '', 12)
            prefs = []
            if diet_prefs.get('vegetarian'): prefs.append('Vegetarian')
            if diet_prefs.get('vegan'): prefs.append('Vegan')
            if diet_prefs.get('gluten_free'): prefs.append('Gluten-Free')
            if diet_prefs.get('dairy_free'): prefs.append('Dairy-Free')
            
            for pref in prefs:
                self.cell(0, 6, f"• {pref}", 0, 1, 'L')
                
    def add_meal_section(self, meal_type, recipe, macros, ingredients):
        """Add a meal section with recipe and ingredients"""
        # Meal title
        self.set_font('Arial', 'B', 16)
        self.set_text_color(41, 84, 144)
        self.cell(0, 10, meal_type.upper(), 0, 1, 'L')
        
        # Recipe name
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, recipe.get('title', 'Custom Meal'), 0, 1, 'L')
        
        # Macros box
        self.ln(2)
        self.set_fill_color(245, 245, 245)
        self.rect(10, self.get_y(), 190, 20, 'F')
        
        # Macros in columns
        y_pos = self.get_y() + 5
        self.set_xy(15, y_pos)
        self.set_font('Arial', 'B', 10)
        
        # Format macro values properly
        calories = int(macros.get('calories', 0)) if macros.get('calories') else 0
        protein = round(float(macros.get('protein', 0)), 1) if macros.get('protein') else 0
        carbs = round(float(macros.get('carbs', 0)), 1) if macros.get('carbs') else 0
        fat = round(float(macros.get('fat', 0)), 1) if macros.get('fat') else 0
        
        self.cell(45, 5, f"Calories: {calories}", 0, 0, 'L')
        self.set_x(60)
        self.cell(45, 5, f"Protein: {protein}g", 0, 0, 'L')
        self.set_x(105)
        self.cell(45, 5, f"Carbs: {carbs}g", 0, 0, 'L')
        self.set_x(150)
        self.cell(45, 5, f"Fat: {fat}g", 0, 1, 'L')
        
        self.ln(15)
        
        # Ingredients
        self.set_font('Arial', 'B', 12)
        self.cell(0, 6, 'INGREDIENTS:', 0, 1, 'L')
        
        self.set_font('Arial', '', 10)
        for ingredient in ingredients:
            if isinstance(ingredient, dict):
                name = ingredient.get('name', 'Unknown')
                amount = ingredient.get('amount', 0)
                self.cell(0, 5, f"- {amount}g {name}", 0, 1, 'L')
            else:
                self.cell(0, 5, f"- {ingredient}", 0, 1, 'L')
        
        # Directions
        directions = recipe.get('directions', [])
        if directions:
            self.ln(3)
            self.set_font('Arial', 'B', 12)
            self.cell(0, 6, 'DIRECTIONS:', 0, 1, 'L')
            
            self.set_font('Arial', '', 10)
            for i, direction in enumerate(directions, 1):
                self.cell(0, 5, f"{i}. {direction}", 0, 1, 'L')
        
        self.ln(8)
        
    def add_grocery_list(self, all_ingredients):
        """Add consolidated grocery list"""
        self.add_page()
        
        self.set_font('Arial', 'B', 18)
        self.set_text_color(41, 84, 144)
        self.cell(0, 12, 'GROCERY LIST', 0, 1, 'L')
        
        # Consolidate ingredients by name
        consolidated = {}
        for ingredient in all_ingredients:
            if isinstance(ingredient, dict):
                name = ingredient.get('name', '').lower()
                amount = float(ingredient.get('amount', 0))
                
                if name in consolidated:
                    consolidated[name] += amount
                else:
                    consolidated[name] = amount
        
        # Sort and display
        self.set_font('Arial', '', 11)
        self.set_text_color(0, 0, 0)
        
        for name, total_amount in sorted(consolidated.items()):
            if name and total_amount > 0:
                self.cell(0, 6, f"- {total_amount:.0f}g {name.title()}", 0, 1, 'L')

def export_meal_plan_pdf(meal_data, user_preferences=None):
    """Export complete meal plan with grocery list to branded PDF"""
    try:
        print("Starting PDF creation...")
        pdf = FitomicsPDF()
        
        # Safely extract plan info with error handling
        total_calories = 0
        total_protein = 0
        total_carbs = 0
        total_fat = 0
        
        print(f"Processing {len(meal_data)} meals...")
        for meal in meal_data.values():
            macros = meal.get('macros', {})
            total_calories += float(macros.get('calories', 0) or 0)
            total_protein += float(macros.get('protein', 0) or 0)
            total_carbs += float(macros.get('carbs', 0) or 0)
            total_fat += float(macros.get('fat', 0) or 0)
        
        plan_info = {
            'total_calories': int(total_calories),
            'total_protein': round(total_protein, 1),
            'total_carbs': round(total_carbs, 1),
            'total_fat': round(total_fat, 1),
            'diet_preferences': user_preferences or {}
        }
        
        print("Adding title page...")
        # Add title page
        pdf.add_title_page({}, plan_info)
        
        print("Adding meals page...")
        # Add meals page
        pdf.add_page()
        pdf.set_font('Arial', 'B', 20)
        pdf.set_text_color(193, 153, 98)  # Fitomics gold
        pdf.cell(0, 12, 'DAILY MEAL PLAN', 0, 1, 'L')
        pdf.ln(5)
        
        all_ingredients = []
        
        for meal_type, meal_info in meal_data.items():
            print(f"Processing meal: {meal_type}")
            recipe = meal_info.get('recipe', {})
            macros = meal_info.get('macros', {})
            ingredients = meal_info.get('ingredient_details', [])
            
            if ingredients:
                all_ingredients.extend(ingredients)
            
            pdf.add_meal_section(meal_type, recipe, macros, ingredients)
        
        print(f"Adding grocery list with {len(all_ingredients)} ingredients...")
        # Add grocery list on new page
        if all_ingredients:
            pdf.add_grocery_list(all_ingredients)
        
        # Save PDF with error handling
        filename = f"fitomics_meal_plan_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
        
        print(f"Saving PDF as {filename}...")
        pdf.output(filename)
        print("PDF created successfully!")
        return filename
        
    except Exception as e:
        print(f"Error creating PDF: {e}")
        print(f"Full traceback: {traceback.format_exc()}")
        return None