#!/usr/bin/env python3
"""
Quick verification test for PDF consolidation
"""
import os
from pdf_export import FitomicsPDF

def test_consolidation_logic():
    """Test just the consolidation algorithm"""
    print("Testing Grocery List Consolidation Logic")
    print("=" * 45)
    
    # Simple test ingredients with duplicates
    test_ingredients = [
        {"name": "Chicken Breast", "amount": "150g"},
        {"name": "Eggs", "amount": "3 large"},
        {"name": "Spinach", "amount": "50g"},
        {"name": "Chicken Breast", "amount": "150g"},  # Duplicate
        {"name": "Eggs", "amount": "2 large"},        # Duplicate
        {"name": "Spinach", "amount": "50g"},         # Duplicate
        {"name": "Brown Rice", "amount": "100g cooked"},
        {"name": "Almonds", "amount": "25g"},
        {"name": "Almonds", "amount": "25g"},         # Duplicate
    ]
    
    print(f"Input: {len(test_ingredients)} ingredient entries")
    
    # Expected results
    expected = {
        "Chicken Breast": "300g (150g + 150g)",
        "Eggs": "5 large (3 + 2)",
        "Spinach": "100g (50g + 50g)", 
        "Brown Rice": "100g cooked (single entry)",
        "Almonds": "50g (25g + 25g)"
    }
    
    print("\nExpected consolidation:")
    for item, total in expected.items():
        print(f"  • {item}: {total}")
    
    # Create PDF and test consolidation
    pdf = FitomicsPDF()
    pdf.add_page()
    
    # Add test grocery list
    pdf.add_grocery_list(test_ingredients)
    
    # Save and check output
    filename = "consolidation_test.pdf"
    pdf.output(filename)
    
    if os.path.exists(filename):
        size = os.path.getsize(filename)
        print(f"\nPDF created: {filename} ({size} bytes)")
        
        # Read and analyze content
        try:
            with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            if "CONSOLIDATED GROCERY LIST" in content:
                print("✅ Grocery list section found")
                
                # Show actual grocery list content
                print("\nActual grocery list content:")
                lines = content.split('\n')
                in_grocery_section = False
                for line in lines:
                    if "CONSOLIDATED GROCERY LIST" in line:
                        in_grocery_section = True
                        continue
                    elif "Generated by Fitomics" in line:
                        in_grocery_section = False
                    elif in_grocery_section and line.strip().startswith('-'):
                        print(f"  {line.strip()}")
                
                # Extract grocery section
                grocery_part = content.split("CONSOLIDATED GROCERY LIST")[1]
                
                # Check consolidation results
                results = {}
                for item in expected.keys():
                    count = grocery_part.count(item)
                    results[item] = count
                    
                    if count == 1:
                        print(f"✅ {item}: Properly consolidated")
                    elif count == 0:
                        print(f"❌ {item}: Missing from grocery list")
                    else:
                        print(f"❌ {item}: Found {count} times (not consolidated)")
                
                # Overall result
                success_count = sum(1 for c in results.values() if c == 1)
                total_items = len(results)
                
                print(f"\nResult: {success_count}/{total_items} items properly consolidated")
                
                if success_count == total_items:
                    print("🎉 Consolidation working perfectly!")
                    return True
                else:
                    print("❌ Consolidation needs fixing")
                    return False
            else:
                print("❌ Grocery list section not found")
                return False
                
        except Exception as e:
            print(f"Error reading PDF: {e}")
            return False
    else:
        print("❌ PDF not created")
        return False

if __name__ == "__main__":
    success = test_consolidation_logic()
    
    if success:
        print("\n✅ VERIFICATION PASSED: Grocery consolidation is working correctly")
    else:
        print("\n❌ VERIFICATION FAILED: Grocery consolidation needs attention")